export const COUNTRIES = [
  { name: "Perú",                code: "PE", dial: "+51",   flag: "🇵🇪" },
  { name: "México",              code: "MX", dial: "+52",   flag: "🇲🇽" },
  { name: "Colombia",            code: "CO", dial: "+57",   flag: "🇨🇴" },
  { name: "Argentina",           code: "AR", dial: "+54",   flag: "🇦🇷" },
  { name: "Chile",               code: "CL", dial: "+56",   flag: "🇨🇱" },
  { name: "Ecuador",             code: "EC", dial: "+593",  flag: "🇪🇨" },
  { name: "Bolivia",             code: "BO", dial: "+591",  flag: "🇧🇴" },
  { name: "Venezuela",           code: "VE", dial: "+58",   flag: "🇻🇪" },
  { name: "Uruguay",             code: "UY", dial: "+598",  flag: "🇺🇾" },
  { name: "Paraguay",            code: "PY", dial: "+595",  flag: "🇵🇾" },
  { name: "Brasil",              code: "BR", dial: "+55",   flag: "🇧🇷" },
  { name: "España",              code: "ES", dial: "+34",   flag: "🇪🇸" },
  { name: "Estados Unidos",      code: "US", dial: "+1",    flag: "🇺🇸" },
  { name: "Canadá",              code: "CA", dial: "+1",    flag: "🇨🇦" },
  { name: "Reino Unido",         code: "GB", dial: "+44",   flag: "🇬🇧" },
  { name: "Alemania",            code: "DE", dial: "+49",   flag: "🇩🇪" },
  { name: "Francia",             code: "FR", dial: "+33",   flag: "🇫🇷" },
  { name: "Italia",              code: "IT", dial: "+39",   flag: "🇮🇹" },
  { name: "Portugal",            code: "PT", dial: "+351",  flag: "🇵🇹" },
  { name: "Panamá",              code: "PA", dial: "+507",  flag: "🇵🇦" },
  { name: "Costa Rica",          code: "CR", dial: "+506",  flag: "🇨🇷" },
  { name: "Guatemala",           code: "GT", dial: "+502",  flag: "🇬🇹" },
  { name: "Honduras",            code: "HN", dial: "+504",  flag: "🇭🇳" },
  { name: "El Salvador",         code: "SV", dial: "+503",  flag: "🇸🇻" },
  { name: "Nicaragua",           code: "NI", dial: "+505",  flag: "🇳🇮" },
  { name: "Cuba",                code: "CU", dial: "+53",   flag: "🇨🇺" },
  { name: "República Dominicana",code: "DO", dial: "+1809", flag: "🇩🇴" },
];

export const PROFESSIONS = [
  "Ingeniero/a",
  "Médico/a / Profesional de salud",
  "Contador/a / Auditor/a",
  "Administrador/a de empresas",
  "Economista",
  "Arquitecto/a",
  "Abogado/a",
  "Docente / Educador/a",
  "Estadístico/a / Matemático/a",
  "Analista de datos / Data Scientist",
  "Desarrollador/a de software",
  "Diseñador/a gráfico/a",
  "Técnico/a",
  "Estudiante universitario/a",
  "Otro",
];
